### ISSUE TITLE
Task: Prendre contact avec les élus et/ou leur représentants

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#14]
# Task description

Le projet prévoit la participation d'élus et/ou de représentants d'élus au niveau des arrondissements et de la ville-centre, nous devons donc initier ce volet en prenant contact avec les personnes d'intérêt.

# Actions

- [ ] Identifier les personnes à contacter au niveau de la ville et des arrondissements
- [ ] Rédiger une lettre d'invitation
- [ ] Valider la lettre auprès de @sjinko et @iolyd
- [ ] Envoyer aux personnes-contacts
