### ISSUE TITLE
Task: Identifier et documenter des exemples de projets à inclure (temporairement) sur la plateforme

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#19]
# Task Description

En parallèle au travail avec les bureaux partenaires, nous devrions recueillir quelques projets qui pourront nous aider à populer la base de données avec un minimum de fiches pour le lancement de la plateforme. Ces projets ne seront pas nécessairement conservés sur la plateforme une fois notre collecte de données plus avancée. IL s'agit d'une stratégie pour nous permettre de populer la base de données le plus tôt possible afin de tester davantage l'implémentation de foncitonnalités et le design de l'interface.

# List of actions

- [x] Identifier des exemples de projets à montréal
- [ ] Contacter les propriétaires et/ou architectes concernés pour demander permission de diffusion temporaire (à titre de test de la plateforme)
- [ ] Colliger les données de base
  - Titre de projet
  - Courte description
  - Type de projet
  - Interventions
  - Galerie d'images

**Comment by emmnull** [comment]
Salut @Sarahprairie, comme il faut avoir un minimum de fiches disponibles sur la plateforme pour cette semaine, je propose que, en parallèle aux ateliers avec les bureaux d'architectes, nous recherchions des projets nous-même. C'est une stratégie dont j'ai discuté avec la personne qui encadre Nplex au bureau du design et nous avons convenu que c'est un moyen pour nous de s'assurer d'avoir un minimum de fiches enregistrées sur la plateforme avant un _deadline_ qui arrive ce vendredi (oui, c'est assez tôt!). Laisse-moi savoir quand tu aurais du temps cette semaine pour en discuter.

**Comment by Sarahprairie** [comment]
Salut @iolyd, je suis disponible demain matin ainsi que jeudi et vendredi toute la journée. Si ça fonctionne pour toi, je le suis également en soirée. Fait moi signe pour ce qui te convient le mieux!

**Comment by emmnull** [comment]
@Sarahprairie, d'accord, allons-y pour demain matin. J'en profiterai aussi pour te présenter brièvement l'avancement sur l'application.

**Comment by Sarahprairie** [comment]
Est-ce que 10h30 fonctionne pour toi ? Je serais à l'université si besoin.

**Comment by emmnull** [comment]
@Sarahprairie, as-tu du temps aujourd'hui pour chercher plus d'exemples de projets? Comme les collaborateurs ne nous on toujours pas envoyé de contenu, j'ai l'impression qu'on devra se contenter de nos propres recherches pour assurer que le livrable d'aujourd'hui puisse illustrer quelques fonctionnalités de la plateforme.

**Comment by Sarahprairie** [comment]
@iolyd Préfères-tu que je t'envoie un document avec toutes les informations pour les projets ou que je crée moi-même les fiches et les envoie pour publication ? Tu n'auras qu'à les relire rapidement et les modifier au besoin. 

J'ai essayé de restreindre le nombre de firmes afin de minimiser le nombre de courriel d'approbation à envoyer.

**Comment by emmnull** [comment]
Je propose que tu crées les fiches sur la plateforme et que'en parallèle tu me partages un document avec les informations. Ça sera l'occasion de tester un peu plus le formulaire avec une autre perspective. Donnes-moi 15 minutes le temps de déployer une petite mise à jour et tu pourras t'y lancer. Ton compte devrais aussi désormais avoir le rôle `editor` donc tu pourras ajouter/modifier certains descripteurs (les indicateurs d'exemplarité et les types d'interventions).

**Comment by emmnull** [comment]
(C'est bon, le site est à jour maintenant)

**Comment by Sarahprairie** [comment]
J'ai envoyé quelques projets pour être publiés, peux-tu me confirmeras si tu les vois également ? 
Aussi lorsque je visite la fiche (hors mode éditeur) je ne vois pas les informations :
<img width="1433" alt="fiche_projet" src="https://user-images.githubusercontent.com/113141268/229215766-9d5e083e-2a5d-4196-afa8-2c17685fc98a.png">

**Comment by emmnull** [comment]
Bien reçu! Je dois compléter la rédaction d'un document avant puis je vérifie dès que possible pour la visibilité des fiches. Autrement, oui c'est normal pour l'instant la page publique des fiches de projet est encore incomplète. J'espérais la compléter avant 17h mais ça devra probablement attendre à plus tard ce soir. Je ferais un suivi lorsque je déploierai une nouvelle version.

**Comment by emmnull** [comment]
Salut @Sarahprairie, pour continuer le travail sur cette tâche, crois-tu pouvoir contacter les architectes ou les propriétaires des projets que tu as insérés sur la plateforme pour demander la permission de diffuser leur projet (en précisant que c'est présentement à titre de fiche-teste pour la plateforme) et valider avec eux le contenu des fiches:

  - Les titres
  - Les textes de description
  - Obtenir les crédits photos là où manquants et demander la permission d'utilisation pour des fiches démo (important). (Je vais m'assurer que les crédits apparaissent sous les images dans l'interface.)
  - Les crédits du projet, i.e. les organismes ayant participé (bureaux d'architectes, arrondissements?, etc.)

**Comment by Sarahprairie** [comment]
Salut @iolyd! 
J'ai déposé un modèle de courriel pour les demandes d'autorisation de diffusion des projets dans le dossier partenariat. Crois-tu que l'on devrait retirer les fiches de leurs projets en attendant leur réponse ou du moins les rendre visible seulement lorsqu'il y a une présentation devant les partenaires ?

**Comment by emmnull** [comment]
Je regarde les modèles de message à l'instant. Oui, en fait je dois les retirer ou ajouter un "watermark" évident en attendant, surtout que la page publique des fiche est encore _in progress_ et peut paraitre brouillon.
