### ISSUE TITLE
Task: Préparer un courriel de reprise de contact avec les bureaux partenaires

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex-organisation#2]
# Task description

Pour lancer la série d'ateliers avec les partenaires, nous devons reprendre contact avec eux.

Partenaires confirmés lors des dernières discussions:

| Partenaire | Personne contact | Fonction | Courriel |
| :-- | :-- | :-- | :-- |
| [**Atelier SUWA**](https://www.s-uwa.ca/) | Lamarre Brodsky, Marie-Ève | Architecte | marie@s-uwa.ca |
| [**La Shed**](https://www.lashedarchitecture.com/) | Laporte, Christian | Coordonateur | info@lashedarchitecture.com |
| [**L. McComber**](https://lmccomber.ca/en/) | Barrette Brisson, Pascale | Associée et Directrice administrative | pascale@lmccomber.ca |
| [**Microclimat**](http://www.microclimat.ca/fr/) | Lajeunesse-Travers, Olivier | Architecte associé | olivier@microclimat.ca |
| [**Pelletier de Fontenay**](http://www.pelletierdefontenay.com/) | Pelletier, Hubert | Architecte, associé principal | hpelletier@pelletierdefontenay.com |
| [**L'Abri**](www.labri.ca) | Richer, Johanne | Gestionnaire des opérations | johanne@labri.ca |

## Rédaction du contenu

Nous avons commencé à préparer une lettre d'invitation générique ici:

https://udemontreal-my.sharepoint.com/:w:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/EYFuCt0MSN9PhOHJa-AkdhMBc6UJaMLBUV1zKQlYx__oMg?e=px8Z6R

Les prochaines communications avec les partenaires devraient inclure:

- Une mise a jour sommaire sur l'état du projet
- _Une demande pour savoir si leur intérêt est toujours présent?_
- Une invitation aux activités convenues précédemment, lors de l'appel à partenariat
- Une précision sur le matériel à préparer pour la conduite de l'activité

À faire probablement en 2 ou 3 temps plutôt qu'avec un seul courriel.

# List of actions

- [x] Rédiger message de relance/invitation
- [x] Rédiger précisions pour matériel à préparer en vue de l'atelier
- [x] Valider le(s) message(s)
- [x] Envoyer aux contacts de chacuns des partenaires confirmés

**Comment by emmnull** [comment]
Salut @Sarahprairie, tu trouveras ici la liste des contacts pour les partenaires qui nous avaient confirmé leur collaboration au printemps dernier. Je vais te transférer les échanges courriels que nous avions eu avec eux dès que j'arrive à les récupérer, tu pourras les utiliser comme point de départ pour les relancer.

**Comment by emmnull** [comment]
En attendant, pour avoir une meilleure idée du format de participation discuté avec les partenaires, je t'invite à consulter les documents ici: https://github.com/CUPUM/nplex-organisation/tree/main/appels

Il s'agit de l'appel à partenariat qui leur a été partagé initialement ainsi que la lettre d'appui proposée. Cette dernière servait en fait de confirmation de participation pour la rédaction d'une demande de financement, elle résumme donc les activités escomptées pour la collaboration des bureaux d'architectes.

**Comment by emmnull** [comment]
Salut @Sarahprairie, j'ai ajouté quelque informations dans la description du issue, dont un lien vers une première version de la lettre de reprise de contact. Il faudrait probablement réviser ladite lettre (mettre à jour avec l'état du projet, formatter un peu, corriger les erreurs, etc.). J'aimerais envoyer les invitation prochainement, crois-tu avoir du temps pour y jeter un coup d'oeil dans les prochains jours?

**Comment by Sarahprairie** [comment]
Salut @iolyd, j'ai quelques petites questions pour toi concernant le contenu des invitations. 
Est-ce qu'on envoie un courriel séparé pour chaque partenaire ou un seul avec tout le monde réuni ? 
Que veut-on dire par : recueillir les impressions concernant les **interactions** sur la plateforme ?
Est-ce que le guide d'exemplarité sera également présenté/complété lors du 3e atelier ?
Pour déposer des documents sur github, je devais créer un nouveau fork, est-ce que c'est également le cas pour nplex ? 
J'attends ta réponse et je dépose les modèles !

**Comment by emmnull** [comment]
> Est-ce qu'on envoie un courriel séparé pour chaque partenaire ou un seul avec tout le monde réuni ?

Jusqu'ici on communiquait avec chaque partenaire séparément. Je continuerais comme ça pour cette première reprise de contact, on pourra fonctionner de manière groupée une fois que chacun nous confirme leur désir de collaborer.

> Que veut-on dire par : recueillir les impressions concernant les interactions sur la plateforme ?

J'en convient, c'est drôlement phrasé :/. En fait c'est simplement pour dire que l'atelier sera organisé non seulement pour entrer des données sur la plateforme, mais aussi pour tester l'interface. L'idée est que les participants devraient avoir en tête qu'ils testent la plateforme, et donc qu'ils n'hésitent aucunnement à donner leur avis sur son "ergonomie", à nous faire part des bugs rencontrés, ou à nous proposer des ajouts ou autres modifications.

> Est-ce que le guide d'exemplarité sera également présenté/complété lors du 3e atelier ?

Idéalement oui, de manière sommaire. On pourra le regarder ensemble prochainement et voir comment le "digérer" pour leur présenter sous une forme plus légère qu'un texte continu. Ça m'aidera aussi à commencer sa mise en forme pour l'intégrer à l'application web.

> Pour déposer des documents sur github, je devais créer un nouveau fork, est-ce que c'est également le cas pour nplex ?

Pas de souci avec les _forks_ ou _branches_ vu qu'on est une petite équipe, tu peux soumettre directement sur la branche principale (`main`) pour garder ça simple :)

**Comment by Sarahprairie** [comment]
J'ai déposé les modèles ici! https://github.com/CUPUM/nplex-organisation

**Comment by emmnull** [comment]
Ça me paraît bien! J'ai apporté quelques petites modifs, et ai réorganisé les documents dans le repo donc n'oublies pas de faire un `pull` pour mettre à jour ta version locale. Aussi, pour nous aider à faire le suivi, je crois que les textes en question ajoutés au repo concernent #3 plutôt que le issue présent?

**Comment by emmnull** [comment]
Salut @Sarahprairie, nous pouvons lancer les invitations pour la série d'ateliers avec les partenaires (#9 sera intégré aux séances individuelles pour simplifier l'horaire des partenaires). Pourrais-tu t'occuper de compléter le modèle d'invitation avec ce lien doodle: https://doodle.com/bp/emmanuelbeaudrymarchand/nplex-ateliers-partenaires-professionnels et l'envoyer à la liste des contacts ci-haut?

**Comment by emmnull** [comment]
Salut @Sarahprairie, as-tu eu l'occasion d'envoyer une première vague d'invitations aux bureaux partenaires?
