### ISSUE TITLE
Task: Rédiger et déposer reddition de compte 3 (finale) à la VdeM

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#21]
# Task Description

Vu le livrable prévu, il est impératif de justifier le lancement reporté de la plateforme dans le contexte d'une coordination planifiée avec d'autres projets menés par la chaire.

> 5.2.2.2
> une somme maximale de sept mille cinq cents dollars (7 500 $) suivant le lancement de la plateforme et la reddition de compte;

## Notes de rencontre avec J. DeGuire (21-04-2023)

- Potentiel moratoire par la chaire sur la diffusion de l'app pour coordonner avec célébrations du 20e
  - Pas de problèmes à reporter la diffusion. Dans la reddition de compte, réitérer par écrit les ententes de la convention et démontrer qu'il y a des démarches en cours, que c'est un chantier pris au sérieux (ex.: «Le titulaire de la chaire en réflexion pour coordonner le lancement de plusieurs projets,...»)
- Questionnement soulevé par partenaires sur viabilité / pertinence des fiches d'intervenant.e.s (individus)
  - Justifiable dans la reddition de compte. Expliquer que le retrait des fiches individus est le résultat d'un constat lors des ateliers de consultation.
- Compléter les fiches des projets actuels !!!
  - Pour les droits d'auteur des images et du contenu, valider auprès des instigateurs des projets (boîtes et arrondissements)
- En ouverture dans la reddition de compte finale, mentionner la subvention supplémentaire de l'udem: démontre que le développement de la plateforme pourra se poursuivre et etc.
- Organisme plusieurs types plutôt que monotype (ex.: `Bureau d'architectes`, `Bureau de design graphique`) ? Ou cadrer différemment... (avec les tags d'expertises?)

# List of actions

- [x] Rédiger le document
- [ ] Soumettre pour validation
- [ ] Apporter corrections nécessaires
- [x] Déposer auprès de J. DeGuire et P. Marmen
