### ISSUE TITLE
Task: Organiser premier atelier avec citoyens et élus

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#4]
### Objectif

Cet atelier servira à recueillir avis sur le cadrage du projet, sur l'interface, et les fonctionnalités, afin d'assurer une adéquation du projet aux réalités autres que celle des employés de la ville et des firmes d'architectes. L'exercice permettra de tester l'interaction utilisateur avec les citoyens et élus, qui constitueront une grande partie des utilisateurs de nplex.

### Déroulement prévu

- Présentation de nplex **20 minutes** (20 min de présentation, 10 min de questions)
  - le projet dans son ensemble
  - la plateforme 
- Exercice de recherche de projet **40 minutes**
  - Co-construire deux mises en situation pertinentes, basées sur leur expérience
  - Chercher un projet répondant à ces critères
  - Quelles ont été les difficultés rencontrées?
- Exploration libre **30 minutes**
  - Y-a-t-il des aspects ou des éléments de nplex qui ont été difficiles à comprendre?
  - Quels éléments ou fonctionnalités de nplex sont vos préférées et pourquoi?

### Participants

| Participant | Affiliation | Rôle |
|--- | --- | --- |
| Emmanuel Beaudry Marchand | CUPUM | Animateur |
| Autre agent ou auxiliaire de recherche? | CUPUM | Animateur |
| Participant.e. 1 | Élu | Participant |
| Participant.e. 2 | Élu | Participant |
| Participant.e. 3 | Élu | Participant |
| Participant.e. 4 | Citoyen | Participant |
| Participant.e. 5 | Citoyen | Participant |
| Participant.e. 6 | Citoyen | Participant |
| Participant.e. 7 | Citoyen | Participant |

### Matériel 
- Salle LIP ou autre salle de rencontre
  -  Écran central
- Ordinateurs portables ou tablettes grand format pour permettre aux participants d'interagir avec l'application
- Application pour enregistrement de l'écran et du microphone afin d'étudier UX et réactions

### Tasks

- [ ] CUPUM/nplex-organisation#7 
- [ ] [Message d'invitation](https://udemontreal-my.sharepoint.com/:w:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/EXwf_-Z0KRhDuLMj-6nfTFkBQQwnpCAAG_VhJ4yt9U2erQ?e=cQlnIV)  - Acceptation d'enregistrement
- [ ] Présentation [figma](https://www.figma.com/file/CTOK91eEnegwRmM68ygj5m/Presentations?node-id=618%3A1350)
