### ISSUE TITLE
Task: Faire suivi courriel pour introduire O. Gauthier au comité de conseil

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#5]
# Task Description

M.E. Lamarre de SUWA (un des partenaires) nous a partagé le contact d'un employé de l'arrondissement Villeray-Saint-Michel-Parc-Extension qui est intéressé à participer au projet. Il faudrait entrer en contact avec ladite personne pour l'introduire au projet et au comité de conseil.

Contact:
> Olivier Gauthier
> olivier.gauthier@montreal.ca
> Villeray-Saint-Michel-Parc-Extension

# List of actions

- [x] Préparer invitation pour O. Gauthier
- [x] Envoyer message d'invitation
- [x] Faire suivi pour invitation (en congé jusqu'au 5 mars)
- [x] Tenir première rencontre d'introduction

**Comment by Sarahprairie** [comment]
Salut @iolyd, avez-vous déjà échangé des messages avec O. Gauthier ? Si oui, quel niveau d"information par rapport au projet et au comité de conseil a-t-il reçu pour que j'ajuste le courriel en conséquence ?

**Comment by emmnull** [comment]
Salut @Sarahprairie, non nous n'avons pas encore échangé avec O. Gauthier. J'ai seulement reçu une référence de la part de la partenaire qui s'est fait communiqué l'intérêt après avoir mentionné notre projet lors d'une discussion avec la mairesse de l'arrondissement VSP (discussion qui ne nous concernait pas directement).

**Comment by emmnull** [comment]
Je ferme ce issue désormais complété. La première rencontre avec O. Gauthier à titre de membre du comité-conseil a eu lieu le 16-03-2023.
