### ISSUE TITLE
Task: Accrédidation OAQ

### ISSUE THREAD

**Issue by EmileForest** [CUPUM/nplex-organisation#8]
# Task description

L'activité entre dans la catégorie 4 de la formation continue, la chaire doit produire pour chaque année de participation : 

- Une attestation pour chaque firme, avec le nombre d'heures réalisées et le type d'implication. Ce nombre d'heures ne peut dépasser 23, sur les 40 permises dans la catégorie 4.

Pour réf., voir catégorie 4 ici: https://www.oaq.com/devoirs-de-larchitecte/formation-continue/obligations-reglementaires/

# Document de travail

https://github.com/CUPUM/nplex-organisation/blob/main/accreditation-oaq/corriveau-model-accreditation_oaq-20220711.docx

# À faire

- [x] Rédiger le modèle d'attestation
  - [ ] Préparer une version pour les membres du comité de conseil
  - [ ] Préparer une version pour les partenaires privés (boîtes d'architecture)
- [ ] Faire signer par Shin
- [ ] Formatter les versions respectives pour chaque partenaire
- [ ] Envoyer aux partenaires APRÈS la tenue des activités

**Comment by emmnull** [comment]
Super, merci pour l'info!
C'est parfait pour la limite d'heures car on indique 20h de travail par firme dans les « ententes » de collaboration.
Devons-nous soumettre les attestations à l'OAQ nous-même ou simplement transférer chaque attestation au partenaire respectif qui la joindra à son dossier?

**Comment by AgathePC** [comment]
@iolyd j'ai fait une première version. J'ajusterai selon tes commentaires.

**Comment by emmnull** [comment]
@Sarahprairie Voici la discussion pour l'accréditation de la participation des partenaires auprès de l'Ordre des architectes du Québec. Il s'agit pour nous en fait simplement de fournir une lettre _officielle_ qui confirme la participation des personnes ressources de chacun des partenaires avec qui nous travaillerons. Le modèle de la lettre est déjà préparé, mais n'hésite pas à y proposer des révisions.
